# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LmsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=10)),
                ('book', models.CharField(max_length=20)),
                ('borrowed', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
            ],
        ),
    ]
