# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmspost',
            name='book',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lmspost',
            name='faculty',
            field=models.CharField(max_length=30),
        ),
    ]
