# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_auto_20160923_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmspost',
            name='borrowed',
            field=models.DateTimeField(),
        ),
    ]
